version: '3'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    networks:
      - internal
    volumes:
      - ./db:/data
  bot:
    image: docker.pkg.github.com/nerdcubed/heleus/heleus:e986492
    restart: always
    depends_on:
      - redis
    networks:
      - internal
    env_file:
      - bot.env
    volumes:
      - ./usercogs:/app/usercogs
      - ./config:/app/config
networks:
  internal:
