description: Cat Bot is a Discord bot for receiving cat and dog pictures on demand, written by DerpyChap.
thumbnail:
    url: https://i.imgur.com/ybGMt1k.png
fields: 
    - name: GitHub Repo
      value: https://github.com/DerpyChap/catbot